#!/usr/bin/env bash
mkdir -p dist
echo "build src/ldup.ls -> dist/ldup.js ..."
./node_modules/.bin/lsc -cbp src/ldup.ls > dist/ldup.js
echo "build src/ldup.styl -> dist/ldup.css ..."
./node_modules/.bin/stylus -p src/ldup.styl > dist/ldup.css
echo "minifying ldup.js ..."
./node_modules/.bin/uglifyjs dist/ldup.js > dist/ldup.min.js
echo "minifying ldup.css ..."
./node_modules/.bin/uglifycss dist/ldup.css > dist/ldup.min.css
echo "copy pug file to dist/ ..."
cp src/ldup.pug dist/ldup.pug
echo "deploy into local web ..."
mkdir -p web/static/assets/lib/ldup/
cp -R dist/* web/static/assets/lib/ldup/
echo "done."

