#!/usr/bin/env bash
mkdir -p dist
echo "build src/client.ls -> dist/uploadr.js ..."
./node_modules/.bin/lsc -cbp src/client.ls > dist/uploadr.js
echo "build src/viewer.ls -> dist/viewer.js ..."
./node_modules/.bin/lsc -cbp src/viewer.ls > dist/viewer.js
echo "build src/server.ls -> dist/server.js ..."
./node_modules/.bin/lsc -cbp src/server.ls > dist/server.js
#echo "build src/uploadr.styl -> dist/uploadr.css ..."
#./node_modules/.bin/stylus -p src/uploadr.styl > dist/uploadr.css
echo "minifying uploadr.js ..."
./node_modules/.bin/uglifyjs dist/uploadr.js > dist/uploadr.min.js
echo "minifying viewer.js ..."
./node_modules/.bin/uglifyjs dist/viewer.js > dist/viewer.min.js
#echo "minifying uploadr.css ..."
#./node_modules/.bin/uglifycss dist/uploadr.css > dist/uploadr.min.css
echo "copy pug file to dist/ ..."
cp src/uploadr.pug dist/uploadr.pug
echo "deploy into local web ..."
mkdir -p web/static/assets/lib/uploadr/
cp -R dist/* web/static/assets/lib/uploadr/
cp dist/server.js web/api/uploadr.js
echo "done."

